name: CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'tex/**'
      - '.github/workflows/latex.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          working_directory: tex
          root_file: |
            main.tex
        
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          path: tex/main.pdf
